- id: '1617768192276'
  alias: Weekday Pink
  description: Makes it pink in the office in the morning
  trigger:
  - platform: time
    at: 07:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.apply
    data:
      entities:
        light.office:
          state: 'on'
          color_name: coral
          brightness_pct: 40
        light.office_desk_light:
          state: 'on'
          color_name: coral
          brightness_pct: 100
        switch.kitchen_light:
          state: 'on'
  mode: single
- id: '1616566126519'
  alias: Office Weekday Morning
  description: Gets Elena's office ready in the morning
  trigger:
  - platform: time
    at: 08:15
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_1
    data:
      transition: 30
  mode: single
- id: '1617158632641'
  alias: Office Weekday Morning 2
  description: ''
  trigger:
  - platform: time
    at: 08:30
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_2
    data:
      transition: 30
  mode: single
- id: '1616643565060'
  alias: Weekday Wind Down
  description: ''
  trigger:
  - platform: time
    at: '21:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.wind_down
    data:
      transition: 30
  mode: single
- id: '1617855367959'
  alias: Bedside Auto Off
  description: ''
  trigger:
  - platform: time
    at: 02:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - type: turn_off
    device_id: 6091d1dd4716f090db1ed154f2614e5b
    entity_id: light.bedside_lamp
    domain: light
  mode: single
- id: '1618247103050'
  alias: Leaving
  description: ''
  trigger:
  - platform: state
    from: home
    to: not_home
    entity_id: group.everyone
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: leaving
      snapshot_entities:
      - light.living_room
      - switch.kitchen_light
      - switch.big_lamp
      - light.bedside_lamp
      - light.hallway_light
      - light.office
      - light.office_desk_light
  - service: scene.apply
    data:
      entities:
        light.living_room:
          state: 'off'
        switch.kitchen_light:
          state: 'off'
        switch.big_lamp:
          state: 'off'
        light.bedside_lamp:
          state: 'off'
        light.hallway_light:
          state: 'off'
        light.office:
          state: 'off'
        light.office_desk_light:
          state: 'off'
  mode: single
- id: '1618261459320'
  alias: Returning
  description: ''
  trigger:
  - platform: state
    entity_id: group.everyone
    from: not_home
    to: home
  - type: opened
    platform: device
    device_id: 9e2536d1e2460fed13aa105c36d2ff24
    entity_id: binary_sensor.front_door
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.leaving
  mode: single
- id: '1618263152733'
  alias: Weekend Late Return
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition:
  - condition: time
    weekday:
    - thu
    - fri
    - sat
  - condition: state
    entity_id: group.everyone
    state: not_home
  action:
  - service: scene.create
    data:
      scene_id: leaving
      entities:
        light.living_room:
          state: 'on'
          color_name: darkorange
          brightness_pct: 50
        light.hallway_light:
          state: 'on'
          color_name: darkorange
          brightness_pct: 1
        light.bedside_lamp:
          state: 'on'
          color_name: red
          brightness_pct: 100
        switch.kitchen_light:
          state: 'on'
        switch.dutch_grow_light:
          state: 'off'
        switch.big_lamp:
          state: 'off'
  mode: single
- id: '1618350936961'
  alias: Elena Return
  description: ''
  trigger:
  - platform: state
    entity_id: person.elena
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: person.john_lancaster
    state: home
  action:
  - service: scene.create
    data:
      snapshot_entities:
      - light.living_room
      - light.hallway_light
      scene_id: elena_return
  - service: scene.apply
    data:
      entities:
        light.living_room:
          state: 'on'
          color_name: steelblue
        light.hallway_light:
          state: 'on'
          color_name: steelblue
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.elena_return
  mode: single
- id: '1619037860061'
  alias: Weekday Awake 1
  description: ''
  trigger:
  - platform: time
    at: 09:30
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - scene: scene.weekday_awake_1
  mode: single
- id: '1619037917337'
  alias: Weekday Awake 2
  description: ''
  trigger:
  - platform: time
    at: '12:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.weekday_awake_2
    data:
      transition: 30
  mode: single
- id: '1619184825513'
  alias: Grow On
  description: ''
  trigger:
  - platform: time
    at: 08:00
  condition: []
  action:
  - type: turn_on
    device_id: b84a9840ce0c61651255a7a36003bfbe
    entity_id: switch.dutch_grow_light
    domain: switch
  - type: turn_on
    device_id: 6429373613100d6d3ff519a9246a8349
    entity_id: switch.grow_cabinet
    domain: switch
  mode: single
- id: '1619184870942'
  alias: Grow Off
  description: ''
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - type: turn_off
    device_id: b84a9840ce0c61651255a7a36003bfbe
    entity_id: switch.dutch_grow_light
    domain: switch
  - type: turn_off
    device_id: 6429373613100d6d3ff519a9246a8349
    entity_id: switch.grow_cabinet
    domain: switch
  mode: single
- id: '1619500515734'
  alias: Weekday Elena Bed
  description: ''
  trigger:
  - platform: time
    at: '22:30'
  - platform: state
    entity_id: binary_sensor.elena_phone_is_charging
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: '21:00'
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.elena_bed
  mode: single
- id: '1620068437298'
  alias: Late Night Short
  description: Turns the lights on temporarily late at night
  trigger:
  - type: motion
    platform: device
    device_id: 8bfd920c1d844c7f43fb3ba53afebf71
    entity_id: binary_sensor.aqara_motion_1
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: light.living_room
    state: 'off'
  - condition: time
    after: '23:00'
    before: 06:00
  action:
  - service: scene.apply
    data:
      entities:
        light.living_room:
          state: 'on'
          color_name: red
          brightness_pct: 10
        light.hallway_light:
          state: 'on'
          color_name: red
          brightness_pct: 10
        switch.kitchen_light:
          state: 'on'
  - delay:
      hours: 0
      minutes: 1
      seconds: 30
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id:
      - light.living_room
      - light.hallway_light
  - type: turn_off
    device_id: 292f607c78277c0aba18f855bf57c869
    entity_id: switch.kitchen_light
    domain: switch
  mode: single
