- id: '1616566126519'
  alias: Office Weekday Morning
  description: Gets Elena's office ready in the morning
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.apply
    data:
      entities:
        light.office:
          state: 'on'
          color_name: deeppink
          brightness_pct: 40
        light.office_desk_light:
          state: 'on'
          color_name: deeppink
          brightness_pct: 100
        switch.kitchen_light:
          state: 'on'
  mode: single
- id: '1617158632641'
  alias: Office Weekday Morning 2
  description: ''
  trigger:
  - platform: time
    at: 08:29
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_1
  mode: single
- id: '1616643565060'
  alias: Weekday Wind Down
  description: ''
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.wind_down
  mode: single