- id: '1616566126519'
  alias: Office Weekday Morning
  description: "Gets Elena's office ready in the morning"
  trigger:
  - platform: time
    at: '07:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - service: scene.apply
    data:
      entities:
        light.office:
          state: 'on'
          color_name: deeppink
        switch.kitchen_light:
          state: 'on'
  mode: single
