- id: '1617768192276'
  alias: Weekday Pink
  description: Makes it pink in the office in the morning
  trigger:
  - platform: time
    at: 07:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.apply
    data:
      entities:
        light.office:
          state: 'on'
          color_name: deeppink
          brightness_pct: 40
        light.office_desk_light:
          state: 'on'
          color_name: deeppink
          brightness_pct: 100
        switch.kitchen_light:
          state: 'on'
  mode: single
- id: '1616566126519'
  alias: Office Weekday Morning
  description: Gets Elena's office ready in the morning
  trigger:
  - platform: time
    at: 08:14
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_1
    data:
      transition: 30
  mode: single
- id: '1617158632641'
  alias: Office Weekday Morning 2
  description: ''
  trigger:
  - platform: time
    at: 08:31
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_2
    data:
      transition: 30
  mode: single
- id: '1616643565060'
  alias: Weekday Wind Down
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.wind_down
  mode: single
- id: '1617855367959'
  alias: Bedside Auto Off
  description: ''
  trigger:
  - platform: time
    at: 02:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - type: turn_off
    device_id: 6091d1dd4716f090db1ed154f2614e5b
    entity_id: light.bedside_lamp
    domain: light
  mode: single
