- id: '1617768192276'
  alias: Weekday Pink
  description: Makes it pink in the office in the morning
  trigger:
  - platform: time
    at: 07:30
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.apply
    data:
      entities:
        light.office:
          state: 'on'
          color_name: coral
          brightness_pct: 40
        light.office_desk_light:
          state: 'on'
          color_name: coral
          brightness_pct: 100
        switch.kitchen_light:
          state: 'on'
        switch.office_grow_light:
          state: 'off'
  - wait_for_trigger:
    - device_id: aecfeae510316cff63a6cc6fa68ff1bd
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    timeout: 01:00:00
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_1
    data: {}
  - wait_for_trigger:
    - device_id: aecfeae510316cff63a6cc6fa68ff1bd
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    timeout: 00:30:00
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_2
  mode: single
- id: '1616566126519'
  alias: Office Weekday Morning
  description: Gets Elena's office ready in the morning
  trigger:
  - platform: time
    at: 09:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: faa23b8679912cea5254870e0935d30f
      entity_id: light.office_desk_light
      domain: light
    - condition: device
      type: is_on
      device_id: f28614685ae41e3be292805bd4493855
      entity_id: switch.office_grow_light
      domain: switch
    - condition: device
      type: is_on
      device_id: 55212266b5370671a1223f5d86c32067
      entity_id: light.office
      domain: light
  action:
  - scene: scene.office_weekday_2
  mode: single
- id: '1617158632641'
  alias: Office Weekday Morning 2
  description: ''
  trigger:
  - platform: time
    at: 09:30
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.office_weekday_2
    data:
      transition: 30
  mode: single
- id: '1616643565060'
  alias: Weekday Wind Down
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '-6'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  - condition: state
    entity_id: group.everyone
    state: home
  - type: is_no_motion
    condition: device
    device_id: b723dd7c8e0cf08743bd091aae21c1a9
    entity_id: binary_sensor.motion_sensor_3
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.wind_down
    data:
      transition: 60
  mode: single
- id: '1617855367959'
  alias: Bedside Auto Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 8a0cd8c6ffbc960f6da9197bf0400f4b
    entity_id: binary_sensor.motion_sensor_2
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: 6091d1dd4716f090db1ed154f2614e5b
    entity_id: light.bedside_lamp
    domain: light
  action:
  - type: turn_off
    device_id: 6091d1dd4716f090db1ed154f2614e5b
    entity_id: light.bedside_lamp
    domain: light
  mode: single
- id: '1618247103050'
  alias: Leaving
  description: ''
  trigger:
  - platform: state
    from: home
    to: not_home
    entity_id: group.everyone
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: leaving
      snapshot_entities:
      - light.living_room
      - switch.kitchen_light
      - switch.big_lamp
      - light.bedside_lamp
      - light.hallway_light
  - service: scene.apply
    data:
      entities:
        light.living_room:
          state: 'off'
        switch.kitchen_light:
          state: 'off'
        switch.big_lamp:
          state: 'off'
        light.bedside_lamp:
          state: 'off'
        light.hallway_light:
          state: 'off'
  - wait_for_trigger:
    - type: opened
      platform: device
      device_id: 9e2536d1e2460fed13aa105c36d2ff24
      entity_id: binary_sensor.front_door
      domain: binary_sensor
  - service: scene.turn_on
    target:
      entity_id: scene.leaving
  mode: single
- id: '1618261459320'
  alias: Returning
  description: ''
  trigger:
  - platform: state
    entity_id: group.everyone
    from: not_home
    to: home
  - type: opened
    platform: device
    device_id: 9e2536d1e2460fed13aa105c36d2ff24
    entity_id: binary_sensor.front_door
    domain: binary_sensor
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.leaving
  mode: single
- id: '1618263152733'
  alias: Weekend Late Return
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition:
  - condition: time
    weekday:
    - thu
    - fri
    - sat
  - condition: state
    entity_id: group.everyone
    state: not_home
  action:
  - service: scene.create
    data:
      scene_id: leaving
      entities:
        light.living_room:
          state: 'on'
          color_name: darkorange
          brightness_pct: 50
        light.hallway_light:
          state: 'on'
          color_name: darkorange
          brightness_pct: 1
        light.bedside_lamp:
          state: 'on'
          color_name: red
          brightness_pct: 100
        switch.kitchen_light:
          state: 'on'
        switch.dutch_grow_light:
          state: 'off'
        switch.big_lamp:
          state: 'off'
  mode: single
- id: '1618350936961'
  alias: Elena Return
  description: ''
  trigger:
  - platform: state
    entity_id: person.elena
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: person.john_lancaster
    state: home
  action:
  - service: scene.create
    data:
      snapshot_entities:
      - light.living_room
      - light.hallway_light
      scene_id: elena_return
  - service: scene.apply
    data:
      entities:
        light.living_room:
          state: 'on'
          color_name: steelblue
        light.hallway_light:
          state: 'on'
          color_name: steelblue
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.elena_return
  mode: single
- id: '1619037860061'
  alias: Weekday Awake 1
  description: ''
  trigger:
  - platform: time
    at: '10:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: device
    type: is_on
    device_id: e19a924a2bd6ba3b04507c1e80e76a16
    entity_id: light.living_room
    domain: light
  action:
  - scene: scene.weekday_awake_1
  mode: single
- id: '1619037917337'
  alias: Weekday Awake 2
  description: ''
  trigger:
  - platform: time
    at: '12:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: device
    type: is_on
    device_id: e19a924a2bd6ba3b04507c1e80e76a16
    entity_id: light.living_room
    domain: light
  action:
  - scene: scene.weekday_awake_2
  mode: single
- id: '1619184825513'
  alias: Grow On
  description: ''
  trigger:
  - platform: time
    at: 08:00
  condition: []
  action:
  - type: turn_on
    device_id: b84a9840ce0c61651255a7a36003bfbe
    entity_id: switch.dutch_grow_light
    domain: switch
  - type: turn_on
    device_id: 6429373613100d6d3ff519a9246a8349
    entity_id: switch.grow_cabinet
    domain: switch
  mode: single
- id: '1619184870942'
  alias: Grow Off
  description: ''
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - type: turn_off
    device_id: b84a9840ce0c61651255a7a36003bfbe
    entity_id: switch.dutch_grow_light
    domain: switch
  - type: turn_off
    device_id: 6429373613100d6d3ff519a9246a8349
    entity_id: switch.grow_cabinet
    domain: switch
  mode: single
- id: '1619500515734'
  alias: Weekday Elena Bed
  description: ''
  trigger:
  - platform: time
    at: '20:30'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: b723dd7c8e0cf08743bd091aae21c1a9
      entity_id: binary_sensor.motion_sensor_3
      domain: binary_sensor
      for:
        hours: 0
        minutes: 15
        seconds: 0
        milliseconds: 0
    - device_id: aecfeae510316cff63a6cc6fa68ff1bd
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  - service: scene.turn_on
    target:
      entity_id: scene.elena_bed
  mode: single
- id: '1620068437298'
  alias: Late Night Short
  description: Turns the lights on temporarily late at night
  trigger:
  - type: motion
    platform: device
    device_id: 8bfd920c1d844c7f43fb3ba53afebf71
    entity_id: binary_sensor.motion_sensor_1
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: light.living_room
    state: 'off'
  - condition: time
    after: '23:00'
    before: 06:00
  - condition: template
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') < 0 }}'
  action:
  - service: scene.apply
    data:
      entities:
        light.living_room:
          state: 'on'
          color_name: red
          brightness_pct: 10
        light.hallway_light:
          state: 'on'
          color_name: red
          brightness_pct: 10
        switch.kitchen_light:
          state: 'on'
      transition: 0
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id:
      - light.living_room
      - light.hallway_light
    data:
      transition: 0
  - type: turn_off
    device_id: 292f607c78277c0aba18f855bf57c869
    entity_id: switch.kitchen_light
    domain: switch
  mode: single
- id: '1620100236063'
  alias: Test Motion Detected
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 8bfd920c1d844c7f43fb3ba53afebf71
    entity_id: binary_sensor.motion_sensor_1
    domain: binary_sensor
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: test_motion
      snapshot_entities:
      - light.living_room
  - service: scene.apply
    data:
      entities:
        light.living_room:
          state: 'on'
          color_name: steelblue
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: 8bfd920c1d844c7f43fb3ba53afebf71
      entity_id: binary_sensor.motion_sensor_1
      domain: binary_sensor
    continue_on_timeout: true
  - service: scene.turn_on
    target:
      entity_id: scene.test_motion
  mode: single
- id: '1620180333704'
  alias: Auto Tracker Update
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 9e2536d1e2460fed13aa105c36d2ff24
    entity_id: binary_sensor.front_door
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: group.everyone
        state: home
      sequence:
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
    default: []
  - service: homeassistant.update_entity
    target:
      entity_id:
      - device_tracker.elena_phone
      - device_tracker.pixel_5
  mode: single
- id: '1620710056967'
  alias: Weekday Off
  description: ''
  trigger:
  - platform: time
    at: '21:30'
  condition: []
  action:
  - wait_for_trigger:
    - device_id: e83999bf18f5ed4c0a22766589cf9ebb
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  - scene: scene.john_bed
  mode: single
- id: '1622069063059'
  alias: Desk Switch Toggle
  description: ''
  trigger:
  - device_id: e83999bf18f5ed4c0a22766589cf9ebb
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: e19a924a2bd6ba3b04507c1e80e76a16
    entity_id: light.living_room
    domain: light
  mode: single
- id: '1622084390458'
  alias: Bedroom Switch Single Press
  description: ''
  trigger:
  - device_id: b37c16eb4ca40658e53024e9241fa5ff
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 6091d1dd4716f090db1ed154f2614e5b
    entity_id: light.bedside_lamp
    domain: light
  mode: single
- id: '1623540859301'
  alias: Office Auto
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: b723dd7c8e0cf08743bd091aae21c1a9
    entity_id: binary_sensor.motion_sensor_3
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - device_id: aecfeae510316cff63a6cc6fa68ff1bd
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: faa23b8679912cea5254870e0935d30f
      entity_id: light.office_desk_light
      domain: light
    - condition: device
      type: is_on
      device_id: f28614685ae41e3be292805bd4493855
      entity_id: switch.office_grow_light
      domain: switch
    - condition: device
      type: is_on
      device_id: 55212266b5370671a1223f5d86c32067
      entity_id: light.office
      domain: light
  action:
  - service: scene.create
    data:
      scene_id: office_auto
      snapshot_entities:
      - light.office
      - light.office_desk_light
      - switch.office_grow_light
  - service: scene.apply
    data:
      entities:
        light.office:
          state: 'off'
        light.office_desk_light:
          state: 'off'
        switch.office_grow_light:
          state: 'off'
  - wait_for_trigger:
    - type: motion
      platform: device
      device_id: b723dd7c8e0cf08743bd091aae21c1a9
      entity_id: binary_sensor.motion_sensor_3
      domain: binary_sensor
    - device_id: aecfeae510316cff63a6cc6fa68ff1bd
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  - choose:
    - conditions:
      - condition: time
        before: 09:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.office_weekday_1
    - conditions:
      - condition: time
        before: '16:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.office_weekday_2
    default:
    - service: scene.turn_on
      target:
        entity_id: scene.office_auto
  mode: single
- id: '1623732730740'
  alias: Bedroom Switch - Double Press
  description: ''
  trigger:
  - device_id: b37c16eb4ca40658e53024e9241fa5ff
    domain: deconz
    platform: device
    type: remote_button_double_press
    subtype: turn_on
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '0'
      sequence:
      - choose:
        - conditions:
          - condition: numeric_state
            entity_id: light.bedside_lamp
            attribute: brightness
            above: '127'
          sequence:
          - service: scene.apply
            data:
              entities:
                light.bedside_lamp:
                  state: 'on'
                  color_temp: 450
                  brightness: 126
        - conditions:
          - condition: numeric_state
            entity_id: light.bedside_lamp
            attribute: brightness
            below: '25'
          sequence:
          - service: scene.apply
            data:
              entities:
                light.bedside_lamp:
                  state: 'on'
                  color_temp: 450
                  brightness: 126
        default:
        - service: scene.apply
          data:
            entities:
              light.bedside_lamp:
                state: 'on'
                color_name: red
                brightness_pct: 5
    default: []
  mode: single
- id: '1623777982523'
  alias: Living Room Auto
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 8bfd920c1d844c7f43fb3ba53afebf71
    entity_id: binary_sensor.motion_sensor_1
    domain: binary_sensor
  - device_id: e83999bf18f5ed4c0a22766589cf9ebb
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  - type: opened
    platform: device
    device_id: 9e2536d1e2460fed13aa105c36d2ff24
    entity_id: binary_sensor.front_door
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: e19a924a2bd6ba3b04507c1e80e76a16
    entity_id: light.living_room
    domain: light
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: '6'
      sequence:
      - choose:
        - conditions:
          - condition: time
            before: '10:00'
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
          sequence:
          - scene: scene.weekday_early
        - conditions:
          - condition: time
            before: '12:00'
            weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
          sequence:
          - scene: scene.weekday_awake_1
        - conditions:
          - condition: time
            weekday:
            - sat
            - sun
          sequence:
          - scene: scene.weekday_awake_1
        default:
        - scene: scene.weekday_awake_2
    default:
    - choose:
      - conditions:
        - condition: time
          before: '23:00'
        sequence:
        - scene: scene.wind_down
      default:
      - service: scene.apply
        data:
          entities:
            light.living_room:
              state: 'on'
              color_name: red
              brightness_pct: 30
  mode: single
- id: '1623799900830'
  alias: Living Room Auto Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 8bfd920c1d844c7f43fb3ba53afebf71
    entity_id: binary_sensor.motion_sensor_1
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: e19a924a2bd6ba3b04507c1e80e76a16
    entity_id: light.living_room
    domain: light
  - type: turn_off
    device_id: b0e896160a9c371588a3bcc02e429524
    entity_id: switch.big_lamp
    domain: switch
  mode: single
