# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

# enable REST API
api:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    homeassistant.loader: info
    homeassistant.components.light.reproduce_state: error

recorder:
  db_url: 'sqlite:///:memory:'
  auto_purge: True
  purge_keep_days: 5

cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
      exclude_entities:
        - light.office_overhead_1
        - light.office_overhead_2
        - light.office_overhead_3
    entity_config:
      light.living_room:
        name: Living Room Pair
        aliases:
          - living room pair
          - main lights
        room: living room

duckdns:
  domain: jslhomeassistant
  access_token: !secret duckdns_token
