# https://www.home-assistant.io/lovelace/dashboards-and-views/

title: The Lola
views:
  - path: default_view
    title: Home
    cards:

      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.living_room
              - entity: switch.dutch_grow_light
              - entity: switch.big_lamp
            title: Living Room
            state_color: true
          - type: entities
            entities:
              - entity: light.bedside_lamp
              - entity: switch.grow_cabinet
            title: Bedroom
            state_color: true
          - type: entities
            entities:
              - entity: light.office
              - entity: light.office_desk_light
            title: Office
            state_color: true
          - title: Other
            type: entities
            entities:
              - entity: light.hallway_light
              - entity: switch.kitchen_light
            state_color: true

      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.the_lola
            secondary_info_attribute: humidity
          - type: history-graph
            entities:
              - entity: sun.sun
              - entity: weather.the_lola
            hours_to_show: 24
            refresh_interval: 0
            title: Sun Location
          - type: entities
            entities:
              - entity: sun.sun
                secondary_info: last-updated
            state_color: true
          - type: entity
            entity: sun.sun
            attribute: elevation
            unit: Degrees above horizon

      - type: entity-filter
        entities:
          - media_player.bedroom_speaker
          - media_player.bedroom_tv
          - media_player.everything
          - media_player.living_room_speaker
          - media_player.living_room_tv
          - media_player.nest_minis
          - media_player.office_speaker
        state_filter:
          - 'playing'
          - 'paused'
        card:
          type: entities
          title: Media

      - type: entities
        entities:
          - entity: scene.wind_down
          - entity: scene.elena_bed
          - entity: scene.john_bed