# https://www.home-assistant.io/lovelace/dashboards-and-views/

title: The Lola
views:
  - path: default_view
    title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - entity: group.everyone
              - entity: person.john_lancaster
              - entity: person.elena
              - entity: binary_sensor.motion_sensor_1
          - type: history-graph
            entities:
              - entity: person.john_lancaster
              - entity: person.elena
              - entity: binary_sensor.front_door
              - entity: binary_sensor.motion_sensor_1
                name: Living Room
              - entity: binary_sensor.motion_sensor_2
                name: Bedroom
              - entity: binary_sensor.motion_sensor_3
                name: Office
            hours_to_show: 18
            refresh_interval: 30
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.living_room
              - entity: switch.dutch_grow_light
              - entity: switch.big_lamp
            title: Living Room
            state_color: true
          - type: entities
            entities:
              - entity: light.bedside_lamp
              - entity: switch.grow_cabinet
            title: Bedroom
            state_color: true
          - type: entities
            entities:
              - entity: light.office
              - entity: light.office_desk_light
              - entity: switch.office_grow_light
            title: Office
            state_color: true
          - title: Other
            type: entities
            entities:
              - entity: light.hallway_light
              - entity: switch.kitchen_light
            state_color: true

      - type: vertical-stack
        cards:
        - type: history-graph
          entities:
            - entity: switch.dutch_grow_light
            - entity: switch.grow_cabinet
          hours_to_show: 24
          refresh_interval: 0
          title: Grow Lights
        - type: entities
          entities:
            - entity: switch.dutch_grow_light
            - entity: switch.grow_cabinet

      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.the_lola
            secondary_info_attribute: humidity
          - type: history-graph
            entities:
              - entity: weather.the_lola
            hours_to_show: 24
            refresh_interval: 0
          - type: entity
            entity: sun.sun
            attribute: elevation
            unit: Degrees above horizon

      - type: entity-filter
        entities:
          - media_player.bedroom_speaker
          - media_player.bedroom_tv
          - media_player.everything
          - media_player.living_room_speaker
          - media_player.living_room_tv
          - media_player.nest_minis
          - media_player.office_speaker
          - media_player.googlehome0584
        state_filter:
          - 'playing'
          - 'paused'
        card:
          type: entities
          title: Media

      - type: entities
        entities:
          - entity: scene.weekday_wakeup
          - entity: scene.weekday_awake_1
          - entity: scene.weekday_awake_2
          - entity: scene.office_weekday_1
          - entity: scene.office_weekday_2
          - entity: scene.wind_down
          - entity: scene.elena_bed
          - entity: scene.john_bed

  - path: temps
    title: Temps
    cards:
      - type: history-graph
        title: 'Graph'
        entities:
          - sensor.bedroom_sensor
          - sensor.outside_sensor
          - sensor.cabinet_sensor
          - sensor.bedroom_sensor_2
          - sensor.outside_sensor_2
          - sensor.cabinet_sensor_2
          - sensor.bedroom_sensor_3
          - sensor.outside_sensor_3
          - sensor.cabinet_sensor_3
