# https://www.home-assistant.io/lovelace/dashboards-and-views/

title: The Lola
views:
  - path: default_view
    title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - entity: group.everyone
              - entity: person.john_lancaster
              - entity: person.elena
              - entity: binary_sensor.aqara_motion_1
          - type: history-graph
            entities:
              - entity: person.john_lancaster
              - entity: person.elena
              - entity: binary_sensor.front_door
              - entity: binary_sensor.aqara_motion_1
                name: Motion
            hours_to_show: 18
            refresh_interval: 30
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: light.living_room
              - entity: switch.dutch_grow_light
              - entity: switch.big_lamp
            title: Living Room
            state_color: true
          - type: entities
            entities:
              - entity: light.bedside_lamp
              - entity: switch.grow_cabinet
            title: Bedroom
            state_color: true
          - type: entities
            entities:
              - entity: light.office
              - entity: light.office_desk_light
            title: Office
            state_color: true
          - title: Other
            type: entities
            entities:
              - entity: light.hallway_light
              - entity: switch.kitchen_light
            state_color: true

      - type: vertical-stack
        cards:
        - type: history-graph
          entities:
            - entity: switch.dutch_grow_light
            - entity: switch.grow_cabinet
          hours_to_show: 24
          refresh_interval: 0
          title: Grow Lights
        - type: entities
          entities:
            - entity: switch.dutch_grow_light
            - entity: switch.grow_cabinet

      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.the_lola
            secondary_info_attribute: humidity
          - type: history-graph
            entities:
              - entity: sun.sun
              - entity: weather.the_lola
            hours_to_show: 24
            refresh_interval: 0
            title: Sun Location
          - type: entities
            entities:
              - entity: sun.sun
                secondary_info: last-updated
            state_color: true
          - type: entity
            entity: sun.sun
            attribute: elevation
            unit: Degrees above horizon

      - type: entity-filter
        entities:
          - media_player.bedroom_speaker
          - media_player.bedroom_tv
          - media_player.everything
          - media_player.living_room_speaker
          - media_player.living_room_tv
          - media_player.nest_minis
          - media_player.office_speaker
          - media_player.googlehome0584
        state_filter:
          - 'playing'
          - 'paused'
        card:
          type: entities
          title: Media

      - type: entities
        entities:
          - entity: scene.weekday_wakeup
          - entity: scene.weekday_awake_1
          - entity: scene.weekday_awake_2
          - entity: scene.office_weekday_1
          - entity: scene.office_weekday_2
          - entity: scene.wind_down
          - entity: scene.elena_bed
          - entity: scene.john_bed

      - type: entities
        entities:
          - entity: automation.weekday_pink
          - entity: automation.office_weekday_morning
          - entity: automation.office_weekday_morning_2
          - entity: automation.weekday_awake_1
          - entity: automation.weekday_awake_2
          - entity: automation.weekday_wind_down
          - entity: automation.weekday_elena_bed
          - entity: automation.bedside_auto_off
          - entity: automation.late_night_short
          - entity: automation.leaving
          - entity: automation.returning
          - entity: automation.weekend_late_return
          - entity: automation.elena_return
          - entity: automation.grow_on
          - entity: automation.grow_off
