dutch_grow_light:
  module: growlight
  class: GrowLight
  entity_id: switch.dutch_grow_light
  start: 'sunrise - 03:00:00'
  duration: '14:00:00'
  end: 'sunset + 00:30:00'

grow_cabinet:
  module: growlight
  class: GrowLight
  entity_id: switch.grow_cabinet
  start: '09:00:00'
  duration: '12:00:00'
  end: '22:00:00'

morning_fader_1:
  module: fader
  class: SceneFader
  start: '06:30:00'
  end: '09:00:00'
  force_initial: True
  initial: Weekday Wakeup
  final: Weekday Awake 1
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri

morning_fader_2:
  module: fader
  class: SceneFader
  start: '09:00:00'
  end: '12:00:00'
  force_initial: True
  initial: Weekday Awake 1
  final: Weekday Awake 2
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri

office_morning_fader:
  module: fader
  class: SceneFader
  start: '08:30:00'
  end: '09:00:00'
  force_initial: True
  initial: Office Weekday 1
  final: Office Weekday 2
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri

wind_down_fader:
  module: fader
  class: SceneFader
  start: 'sunset'
  end: '22:00:00'
  force_initial: True
  initial: Wind Down
  final: Elena Bed
  weekday:
    - sun
    - mon
    - tue
    - wed
    - thu

test:
  module: pandas_controller
  class: PandasCtl
  start: '00:00:00'
  end: '23:00:00'
  freq: '15min'
#  initial: 'scene.weekday_awake_2'
#  final: 'scene.wind_down'
  initial: seagreen
  final: steelblue
#  initial:
#    brightness_pct: 1
#    color_temp: 200
#  final:
#    brightness_pct: 100
#    color_temp: 400