dutch_grow_light:
  module: light_control
  class: GrowLight
  entity_id: switch.dutch_grow_light
  start: 'sunrise - 03:00:00'
  duration: '14:00:00'
  end: 'sunset + 00:30:00'

living_room_fade:
  module: light_control
  class: TimeFader
  entity_id: light.living_room_lights
  start: 'sunrise - 1:00:00'
  end: '11:00:00'
  initial:
    brightness: 5
    color_temp: 230
  final:
    brightness: 80
    color_temp: 375