dutch_grow_light:
  module: light_control
  class: GrowLight
  entity_id: switch.dutch_grow_light
  start: 'sunrise - 03:00:00'
  duration: '14:00:00'
  end: 'sunset + 00:30:00'

grow_cabinet:
  module: light_control
  class: GrowLight
  entity_id: switch.grow_cabinet
  start: '09:00:00'
  duration: '12:00:00'
  end: '22:00:00'

morning_bedroom:
  module: light_control
  class: TimeFader
  entity_id: light.living_room_lights
  start: 'sunrise - 00:30:00'
  end: '09:00:00'
  initial:
    brightness: 5
    color_temp: 650
  final:
    brightness: 40
    color_temp: 250

living_room_morning:
  module: light_control
  class: TimeFader
  entity_id: light.living_room_lights
  start: 'sunrise - 1:00:00'
  end: '11:00:00'
  initial:
    brightness: 5
    color_temp: 200
  final:
    brightness: 80
    color_temp: 300

living_room_evening:
  module: light_control
  class: TimeFader
  entity_id: light.living_room_lights
  start: '16:00:00'
  end: 'sunset + 02:00:00'
  initial:
    brightness: 80
    color_temp: 350
  final:
    brightness: 50
    color_temp: 450